### ISSUE TITLE
Different keybind

### ISSUE THREAD

**Issue by DeVelox** [steven4547466/YoutubeBoombox#3]
Would it be possible to have this on a different keybind so it doesn't replace the base boombox functionality?

**Comment by steven4547466** [comment]
Potentially, though I may reverse the idea and make it so the keybind instead does the normal functionality. Mainly because this would require a small rework and people are used to it just replacing the base functionality. Or I could just have it say like "Press KEY to play a youtube song" or something along those lines so people know what to do.

So to answer your question, maybe. I'll leave this open as a reminder to myself

**Comment by DeVelox** [comment]
Thanks, reverse is fine as well, it'd just be nice to keep the convenience of getting a random song from a music pack.

**Comment by steven4547466** [comment]
Next update will introduce a configurable keybind for the YT gui

**Comment by steven4547466** [comment]
Added in v1.4.0
